### ISSUE TITLE
How to add new prompts to drop-down menu in Firefox

### ISSUE THREAD

**Issue by neowit** [smoqadam/chatgpt-toolbox#1]
Hello @smoqadam,

Thank you for making this extension available in Firefox. I have tried several similar extensions and found this one the most user-friendly.

Question - is there any way to modify the drop down menu in firefox, i.e. add new values, modify/remove existing ones?

![prompts](https://github.com/smoqadam/chatgpt-toolbox/assets/552057/7212ae1c-b97b-4548-9441-a9c689bcd9e2)

Thank you

**Comment by smoqadam** [comment]
Hi @neowit ,

Currently, it's not possible but I have a plan to add this functionality in the next couple of weeks, I'm just a bit busy these days.

**Comment by smoqadam** [comment]
Hi @neowit, 

The new version is up with customizable prompts. 

https://addons.mozilla.org/en-US/firefox/addon/chatgpt-toolbox/

**Comment by neowit** [comment]
That's great. Thank you very much @smoqadam
